### ISSUE TITLE
Fix Gitter sag in README

### ISSUE THREAD

**Issue by MiloATH** [c4milo/fusejs#36]
The second line of the readme has a button to the Gutter chat, but the svg isn't loading. The issue is the space in the link to the svg. The correct second line is: `[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/c4milo/fusejs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
`
The space needs to be replaced with a `%20` in the `https://badges.gitter.im/Join Chat.svg` link.

**Comment by c4milo** [comment]
Closed by #37
