### ISSUE TITLE
Fuzzy searching a tree of items

### ISSUE THREAD

**Issue by aminya** [c4milo/fusejs#40]
I need to fuzzy search a tree of items. Each item may have some children (`item.children`), and each child could be an item itself. It can be a recursive thing. 

Is there a way to use fusejs for that?

**Comment by Merlin04** [comment]
I think you have made an issue on the wrong fusejs, this one is a wrapper for FUSE (a library to create filesystems).

**Comment by aminya** [comment]
Oh, sorry.
